sudo: required

language: node_js
node_js: "6"

cache:
  yarn: true

env:
  global:
    - "NODE_ENV=test"
    - "NODE_DB_USER=travis"
    - "NODE_DB_PASS=test"
    - "NODE_DB_HOST=127.0.0.1"
    - "NODE_DB_PORT=27017"
    - "NODE_DB_BASE=susanin_test"

services:
  - docker
  - mongodb

before_install:
  # Mongo
  - "mongo ${NODE_DB_BASE} --eval 'db.createUser({ user: \"${NODE_DB_USER}\", pwd: \"${NODE_DB_PASS}\", roles: [\"readWrite\", \"dbAdmin\" ] );'"
  # Instal deps
  - "npm install -g yarn"
  - "yarn install --global coveralls istanbul"
  - "(NODE_ENV=development && yarn install --ignore-scripts --no-progress)"
  - "yarn ls"

script:
  # Lint
  - "npm run lint"
  # Build
  - "(NODE_ENV=production && npm run build:clear)"
  - "(NODE_ENV=production && npm run build:images)"
  - "(NODE_ENV=production && npm run build:icons)"
  - "(NODE_ENV=production && npm run build:server)"
  - "(NODE_ENV=production && npm run build:client)"
  # Test
  - "npm run test-ci"
  # Docker
  - "docker build -t superpaintman/susanin:latest ."

after_script:
  # coveralls
  - "cat ./coverage/lcov.info | coveralls"

branches:
  except:
    - gh-pages